services:
  - type: web
    name: whatsapp-bot
    env: node
    plan: free
    region: oregon
    buildCommand: npm install && npx puppeteer install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: false
